### ISSUE TITLE
Undefined index: dh

### ISSUE THREAD

**Issue by shahzadthathal** [bupy7/yii2-widget-cropbox#10]
I'm using 2.2 version of your extension.

If I browsed the image in my form and click on save button without clicking on crop button, I got this error Undefined index: dh,
There should be some kind of handler , if crop button not clicked, then upload only image don't create thumbnail or create thumbnail of original image.

Thank you.

**Comment by bupy7** [comment]
You need check at uploading file. If image not exists then why it need saving?

**Comment by shahzadthathal** [comment]
Hi
Image exist but I tried to save image without click on Crop button and got this error.

**Comment by bupy7** [comment]
Cropping is required.

**Comment by shahzadthathal** [comment]
Sometime if some one don't want to crop the image :)

**Comment by bupy7** [comment]
@shahzadthathal Then check crop info field at information about crop. If

**Comment by shahzadthathal** [comment]
okay Thanks :+1:

**Comment by havoe** [comment]
why Setting unknown property: bupy7\cropbox\Cropbox::optionsCropbox?

**Comment by bupy7** [comment]
write me version of cropbox
—
С ув., Василий.

14 янв. 2016 г., в 20:11, 小酒酒 <notifications@github.com> написал(а):

**Comment by havoe** [comment]
"bupy7/yii2-widget-cropbox": "*",

**Comment by havoe** [comment]
{
    "name": "bupy7/yii2-widget-cropbox",
    "description": "This is widget wrapper of https://github.com/bupy7/jquery-cropbox. This widget allows crop image before upload to server and send informations about crop in JSON format.",
    "keywords": ["yii2", "extension", "widget", "crop image", "image"],
    "homepage": "https://github.com/bupy7/yii2-widget-cropbox",
    "version": "4.0.0",
    "type": "yii2-extension",
    "license": "BSD 3-Clause",
    "authors": [
        {
            "name": "Vasilij Belosludcev",
            "email": "bupy765@gmail.com",
            "homepage": "http://mihaly4.ru"
        }
    ],
    "minimum-stability": "stable",
    "require": {
        "yiisoft/yii2-bootstrap": "*",
        "bower-asset/jq-cropbox": "1.0.*"
    },
    "autoload": {
        "psr-4": {
            "bupy7\\cropbox\\": ""
        }
    }
}

**Comment by bupy7** [comment]
4 version different between 3 version. You need rewrite configuration in call widget or use 3 version.
—
С ув., Василий.

14 янв. 2016 г., в 20:11, 小酒酒 <notifications@github.com> написал(а):

**Comment by havoe** [comment]
谢谢！

**Comment by tedyonly** [comment]
When I save the message 'File D:\xampp\tmp\php95FA.tmp doesn't exist', please help.

**Comment by bupy7** [comment]
@tedyonly check availability `enctype` to your a form
```php
$form = ActiveForm::begin([
    'options' => ['enctype'=>'multipart/form-data'],
]);
```
