### ISSUE TITLE
Change Event Listener

### ISSUE THREAD

**Issue by bvanleeuwen1995** [bupy7/yii2-widget-cropbox#14]
For a project that I'm currently working on I use the cropbox, and I'm really loving it so far.

On little problem that I do have, is that whenever the plugin is enabled, the on(change) event listener behaves strangly on my select box, it has a size attribute, and once it has that, the on change does not register mouse clicks anymore, this problem is over when I desable the loading of this plugin.

Does somebody have a  work around for this, ore a fix?

**Comment by bupy7** [comment]
Hi! **yii2-widget-cropbox** it wrapper of [jquery-cropbox](https://github.com/bupy7/jquery-cropbox). All questions by work of plugin you need send to **jquery-cropbox**.

**Comment by bupy7** [comment]
Hm.. Which version of yii2-widget-cropbox you uses?

**Comment by bvanleeuwen1995** [comment]
Thank you for you response, I'm currently on 4.0.0

**Comment by bupy7** [comment]
@bvanleeuwen1995 You need open issue to [jquery-cropbox](https://github.com/bupy7/jquery-cropbox) and generate it situation via https://jsfiddle.net/
