### ISSUE TITLE
Update form

### ISSUE THREAD

**Issue by bvanleeuwen1995** [bupy7/yii2-widget-cropbox#16]
Hello,

Is there a way to show the cropped image when we update the record? We are currently saving the cropped image to our server, which is working great, but I also want it that when we update our record, it shows the cropped image.

Bob

**Comment by bupy7** [comment]
@bvanleeuwen1995 At the moment, this function not supported for `jquery-cropbox`. As soon as author of `jquery-cropbox` (it's me :D) will make this opportunity then I necessarily add this in `yii2-widget-cropbox`. You can accelerate this process if you make pull-request for  [jquery-cropbox](https://github.com/bupy7/jquery-cropbox) with that functionality.

**Comment by bupy7** [comment]
Don't answer.

**Comment by bupy7** [comment]
No answer.
