### ISSUE TITLE
how to resize/crop and save cropped image

### ISSUE THREAD

**Issue by harry-promogata** [bupy7/yii2-widget-cropbox#20]
thanks.. this is a smart tools, but i found some trouble for my case:

1. how to resize/crop and save cropped image without use models (using controller)
2. i got error in model (function aftersave(){} )
	$image = Image::getImagine()->open($this->image->tempName); 
      - what the meaning of tempName?

error say:  PHP Notice – yii\base\ErrorException
Trying to get property of non-object

**Comment by bupy7** [comment]
1. use controllers it is bad way. this widgets does not force follow examples upload image. it only examples :) and this widget is only wrapper of jquery-cropbox plugin.
2. https://github.com/yiisoft/yii2/blob/master/framework/web/UploadedFile.php#L40

**Comment by harry-promogata** [comment]
oh.. i copy that.
thanks bupy
