### ISSUE TITLE
Undefined offset: 0

### ISSUE THREAD

**Issue by shahzadthathal** [bupy7/yii2-widget-cropbox#21]
I got this issue:

Undefined offset: 0
![erro-imag-crp](https://cloud.githubusercontent.com/assets/4338236/14637050/61c148f4-0648-11e6-8962-babeef4a8eda.png)

**Comment by bupy7** [comment]
Show me `var_dump($this->crop_info)`;

**Comment by Lordfef** [comment]
in my case i had this error when i sumbit my form without cropping the image

**Comment by bupy7** [comment]
@shahzadthathal 
```php
if (!empty($this->crop_info[0])) {
    // crop image
}
```

**Comment by Lordfef** [comment]
thank's  @bupy7 i think also your solution, but i think is better to manage it client side before validation. It's possible?

**Comment by bupy7** [comment]
@Lordfef add this code in a custom validator

**Comment by bupy7** [comment]
> The reason for closing: No answer.

**Comment by bupy7** [comment]
> The reason for closing: No answer.
