### ISSUE TITLE
There are a lot of bugs

### ISSUE THREAD

**Issue by zakdma** [bupy7/yii2-widget-cropbox#23]
There are a lot of bugs in this module. It behaviour is inadequat.
I don't know how you don't see bugs.
Please refer to the video.
https://youtu.be/OimD-qgAS_0 
I have used DEMO http://bupy7.github.io/jquery-cropbox/
I clicked mouse only once or two to resize selection. After that it stuck to mouse pointer and resized every time I moved mouse without clicking.

**Comment by bupy7** [comment]
These bugs there are not everyone. Only if uses a mouse control: https://github.com/bupy7/jquery-cropbox/issues/5

**Comment by zakdma** [comment]
Ok. Appologize, it is not you fault.
