### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by Flashwade1990** [bupy7/yii2-widget-cropbox#30]
Is there a way to respond to events, e.g. do something when an image was uploaded or when it was cropped?

**Comment by bupy7** [comment]
Which you using version of widget?

**Comment by Flashwade1990** [comment]
Verson 4.1.1

**Comment by bupy7** [comment]
Since 4.0.0 `yii2-widget-cropbox` is wrapper of [https://github.com/bupy7/jquery-cropbox](jquery-cropbox). All questions about JS need to write to `jquery-cropbox`.

Answering your question: No events any. If you want you can added ones to the plugin.
