### ISSUE TITLE
Как использовать ratio?

### ISSUE THREAD

**Issue by Dimabiz** [bupy7/yii2-widget-cropbox#34]
Здравствуйте, хотел бы чтобы область для обрезания была с определенным соотношением сторон, поддерживает ли плагин такую возможность? Если нет, очень хотелось бы чтобы добавили. Заранее спасибо.

**Comment by bupy7** [comment]
Здравствуйте. В лоб не поддерживает, т.е. указать что-то вроде `16:9`... Но такая возможность есть, к примеру, `200px`X`100px` - это, `2:1`, а `500px`X`200px` - это, `5:2`. Указывайте такой размер и пользуйтесь [примером](https://github.com/bupy7/yii2-widget-cropbox#crop-with-save-real-size-of-image).

_**P.S.** Желательно здесь писать на английском, чтобы у других людей не владеющих русским языком была возможность тоже получить ответ, если будет такой же вопрос._
