### ISSUE TITLE
Undefined index: cropSettings

### ISSUE THREAD

**Issue by hfageeh** [bupy7/yii2-widget-cropbox#36]
I dont know what wrong I just install it as you said step by step please advise

**Comment by bupy7** [comment]
What version of cropbox?

**Comment by hfageeh** [comment]
3.0

**Comment by hfageeh** [comment]
view:

<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use bupy7\cropbox\Cropbox;
/* @var $this yii\web\View */
/* @var $model backend\models\Projectsgroups */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="projectsgroups-form">

    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]) ?>
    <?= $form->field($model, 'image')->widget(Cropbox::className(), [
    'attributeCropInfo' => 'crop_info',
]); ?> 
    
    <?= $form->field($model, 'order')->textInput() ?>
    
   <?= $form->field($model, 'ar_groupname')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'en_groupname')->textInput(['maxlength' => true]) ?>

    

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

**Comment by hfageeh** [comment]
model:

<?php

namespace backend\models;

use Yii;
use yii\helpers\FileHelper;
use yii\imagine\Image;
use yii\helpers\Json;
use Imagine\Image\Box;
use Imagine\Image\Point;
/**
 * This is the model class for table "projectsgroups".
 *
 * @property integer $projgroup_id
 * @property string $ar_groupname
 * @property string $en_groupname
 * @property string $imageFile
 * @property string $created
 * @property integer $createdby
 * @property string $modified
 * @property string $file
 * @property integer $modifiedby
 * @property integer $order
 *
 * @property Projects[] $projects
 */
class Projectsgroups extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public $file;
    public $crop_info;
    public static function tableName()
    {
        return 'projectsgroups';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['ar_groupname', 'en_groupname', 'imageFile', 'order'], 'required'],
            [['created', 'modified'], 'safe'],
            [['createdby', 'modifiedby', 'order'], 'integer'],
            [['ar_groupname', 'en_groupname'], 'string', 'max' => 100],
            [['imageFile'], 'string', 'max' => 255],
            [
            'image', 
            'image', 
            'extensions' => ['jpg', 'jpeg', 'png', 'gif'],
            'mimeTypes' => ['image/jpeg', 'image/pjpeg', 'image/png', 'image/gif'],
            ],
             ['crop_info', 'safe'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'projgroup_id' => Yii::t('app', 'Projgroup ID'),
            'ar_groupname' => Yii::t('app', 'Arabic Groupname'),
            'en_groupname' => Yii::t('app', 'English Groupname'),
            'imageFile' => Yii::t('app', 'Image File'),
            'image' => Yii::t('app', 'Groupimg'),
            'created' => Yii::t('app', 'Created'),
            'createdby' => Yii::t('app', 'Createdby'),
            'modified' => Yii::t('app', 'Modified'),
            'modifiedby' => Yii::t('app', 'Modifiedby'),
            'order' => Yii::t('app', 'Order'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProjects()
    {
        return $this->hasMany(Projects::className(), ['projgroup_id' => 'projgroup_id']);
    }
    public function afterSave($insert, $changedAttributes)
{
    // open image
    $image = Image::getImagine()->open($this->image->tempName);

    // rendering information about crop of ONE option 
    $cropInfo = Json::decode($this->crop_info)[0];
    $cropInfo['dWidth'] = (int)$cropInfo['dWidth']; //new width image
    $cropInfo['dHeight'] = (int)$cropInfo['dHeight']; //new height image
    $cropInfo['x'] = $cropInfo['x']; //begin position of frame crop by X
    $cropInfo['y'] = $cropInfo['y']; //begin position of frame crop by Y
    // Properties bolow we don't use in this example
    //$cropInfo['ratio'] = $cropInfo['ratio'] == 0 ? 1.0 : (float)$cropInfo['ratio']; //ratio image. 
    //$cropInfo['width'] = (int)$cropInfo['width']; //width of cropped image
    //$cropInfo['height'] = (int)$cropInfo['height']; //height of cropped image
    //$cropInfo['sWidth'] = (int)$cropInfo['sWidth']; //width of source image
    //$cropInfo['sHeight'] = (int)$cropInfo['sHeight']; //height of source image

    //delete old images
    $oldImages = FileHelper::findFiles(Yii::getAlias('@path/to/save/image'), [
        'only' => [
            $this->id . '.*',
            'thumb_' . $this->id . '.*',
        ], 
    ]);
    for ($i = 0; $i != count($oldImages); $i++) {
        @unlink($oldImages[$i]);
    }

    //saving thumbnail
    $newSizeThumb = new Box($cropInfo['dWidth'], $cropInfo['dHeight']);
    $cropSizeThumb = new Box(200, 200); //frame size of crop
    $cropPointThumb = new Point($cropInfo['x'], $cropInfo['y']);
    $pathThumbImage = Yii::getAlias('@path/to/save/image') 
        . '/thumb_' 
        . $this->id 
        . '.' 
        . $this->image->getExtension();  

    $image->resize($newSizeThumb)
        ->crop($cropPointThumb, $cropSizeThumb)
        ->save($pathThumbImage, ['quality' => 100]);

    //saving original
    $this->image->saveAs(
        Yii::getAlias('@path/to/save/image') 
        . '/' 
        . $this->id 
        . '.' 
        . $this->image->getExtension()
    );
}
}

**Comment by hfageeh** [comment]
controller:
public function actionCreate()
    {
        $model  = new Projectsgroups();
        //$upload = new UploadForm();
        if ($model->load(Yii::$app->request->post())) 
        {
            // get uploaded file information
            $groupName = strtolower($model->en_groupname);
            $imageName = str_replace(' ', '',$groupName );;
            $model->image = UploadedFile::getInstance($model, 'image');
            $model->image->saveAs('../../frontend/web/images/project/' . $imageName.'.'.$model->image->extension);
            
            // save the path in DB 
            $model->imageFile = $imageName.'.'.$model->image->extension;
            $model->created = date('Y-m-d h:m:s');
            $model->save();
            
       
            return $this->redirect(['view', 'id' => $model->projgroup_id]);
            } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

**Comment by bupy7** [comment]
Wow, very dirty... You should wrap you code in markdown code tag, please.

Could you give me screenshot of the error message?

**Comment by hfageeh** [comment]
<img width="960" alt="error" src="https://cloud.githubusercontent.com/assets/6096313/25247300/23ddae4c-2613-11e7-936a-97643babb2c0.png">

**Comment by bupy7** [comment]
It's a bug. You can fix it following code:

```
<?= $form->field($model, 'image')->widget(Cropbox::className(), [
    'attributeCropInfo' => 'crop_info',
    'optionsCropbox' => [
        'cropSettings' => [],
    ],
]); ?>
```

**Comment by hfageeh** [comment]
The 'icon-framework' option has not been setup in Yii params. Check your configuration file.

**Comment by bupy7** [comment]
https://github.com/kartik-v/yii2-icons#global-setup

**Comment by hfageeh** [comment]
its work you the man 💯
