### ISSUE TITLE
Select Wrong Image Type

### ISSUE THREAD

**Issue by skworden** [bupy7/yii2-widget-cropbox#4]
If you select anything that isn't considered valid i.e. .docx it will still open the crop field and lock everything.

break

It would be nice if there was an edit/recrop button.

I.e A user upload an image and cropped it. They could want to recrop it before saving.  You have to reselect the image if you want to crop it again.

It would also be nice to have a remove image / clear button. A user may select an image then want to remove it and not save one.
````
var control = $("#image-file");
    $(".btnClear").on("click", function() {
        control.replaceWith(control = control.clone(true));
        $("#cropInfo").val('');
        $(".cropped").html('');
    });
````

**Comment by bupy7** [comment]
Hi! This is good a proposals. I add it to new version of extension. Thanks!
