### ISSUE TITLE
How to make the plugin work with mobile devices? (For Panning and zooming)

### ISSUE THREAD

**Issue by nivedhar** [bupy7/yii2-widget-cropbox#46]

**Comment by bupy7** [comment]
Sorry for long answer. Panning feature didn't implement. Zooming you can do using cropbox.scale() method.

**Comment by nivedhar** [comment]
Can you please give some idea of how to implement panning effect in mobile?

**Comment by bupy7** [comment]
For it need to add mobile support in the extension. It will take rather long time. You can upgrade the extension and after send me pull-request. Unfortunately, now I have not time for this job.
