### ISSUE TITLE
Please, add support for custom callbacks from widget

### ISSUE THREAD

**Issue by Insolita** [bupy7/yii2-widget-cropbox#51]
I can't see a proper way to attach a custom callback on 'cb:cropped' event

**Comment by bupy7** [comment]
Something like this:

```js
$('.cropbox .plugin').cropbox('getCb').addEventListener('cb:cropped', function(event) {
  // your code
});
```

**Comment by Insolita** [comment]
Good, thanks! But will be better if this ability will be provided by a widget anyway

**Comment by bupy7** [comment]
You can help me with PR if you want.

**Comment by bupy7** [comment]
We should not mix js and php, therefore the suggestion cannot be added. Please, use plain js.
