### ISSUE TITLE
Trying to get property of non-object

### ISSUE THREAD

**Issue by shahzadthathal** [bupy7/yii2-widget-cropbox#9]
Hi,

Great work,
There is issue when I update my model, there is no option to crop the uploaded image again and If I click on update button I got this error in my Model, at line 74

72     public function afterSave($insert, $changedAttributes) { 
 73       // open image
74        $image = Image::getImagine()->open($this->icon->tempName);

**Comment by bupy7** [comment]
You need check at exists image file for uploading.

```php
if ($this->icon) {
    // there saving
}
```

**Comment by shahzadthathal** [comment]
Thank you, will try.
